<a href="https://colab.research.google.com/github/Praj24-04/Machine-Learning/blob/main/MLPrac1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import kagglehub

path = kagglehub.dataset_download("arnavgupta1205/usa-housing-dataset")
print(path)

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (0.4.1).
Downloading from https://www.kaggle.com/api/v1/datasets/download/arnavgupta1205/usa-housing-dataset?dataset_version_number=1...

100%|██████████| 6.28k/6.28k [00:00<00:00, 12.4MB/s]

Extracting files...
/root/.cache/kagglehub/datasets/arnavgupta1205/usa-housing-dataset/versions/1

In [ ]:
import pandas as pd
import numpy as np
import os

In [ ]:
os.listdir(path)

['usa_housing_kaggle.csv']

In [ ]:
df = pd.read_csv(f"{path}/usa_housing_kaggle.csv")

In [ ]:
df.head()

,Price,Bedrooms,Bathrooms,SquareFeet,YearBuilt,GarageSpaces,LotSize,ZipCode,CrimeRate,SchoolRating
0,221958,1,1.9,4827,1979,2,1.45,82240,48.60,5
1,771155,2,2.0,1035,1987,2,1.75,74315,92.03,9
2,231932,1,3.0,2769,1982,1,1.46,79249,52.08,3
3,465838,3,3.3,2708,1907,3,1.62,80587,61.65,1
4,359178,4,3.4,1175,1994,2,0.74,20756,15.66,4

#[1] Object Creation

---

In [ ]:


students = pd.DataFrame({
    'Student_ID': [101, 102, 103, 104, 105],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [20, 21, 19, 22, 20],
    'Gender': ['F', 'M', 'M', 'M', 'F'],
    'Department': ['CS', 'IT', 'CS', 'ECE', 'IT'],
    'Marks': [85, 78, 92, 88, 90],
    'Attendance': [90, 85, 95, 88, 92],
    'Internship': ['Yes', 'No', 'Yes', 'Yes', 'No']
})

# [2] Viewing Data

---

In [ ]:
students

   Student_ID     Name  Age Gender Department  Marks  Attendance Internship
0         101    Alice   20      F         CS     85          90        Yes
1         102      Bob   21      M         IT     78          85         No
2         103  Charlie   19      M         CS     92          95        Yes
3         104    David   22      M        ECE     88          88        Yes
4         105      Eva   20      F         IT     90          92         No

In [ ]:
students.head()

   Student_ID     Name  Age Gender Department  Marks  Attendance Internship
0         101    Alice   20      F         CS     85          90        Yes
1         102      Bob   21      M         IT     78          85         No
2         103  Charlie   19      M         CS     92          95        Yes
3         104    David   22      M        ECE     88          88        Yes
4         105      Eva   20      F         IT     90          92         No

In [ ]:
students.tail()

   Student_ID     Name  Age Gender Department  Marks  Attendance Internship
0         101    Alice   20      F         CS     85          90        Yes
1         102      Bob   21      M         IT     78          85         No
2         103  Charlie   19      M         CS     92          95        Yes
3         104    David   22      M        ECE     88          88        Yes
4         105      Eva   20      F         IT     90          92         No

In [ ]:
students.shape

(5, 8)

In [ ]:
students.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
students.columns

Index(['Student_ID', 'Name', 'Age', 'Gender', 'Department', 'Marks',
       'Attendance', 'Internship', 'Total_Score'],
      dtype='object')

In [ ]:
students.to_numpy()

array([[101, 'Alice', 20, 'F', 'CS', 85, 90, 'Yes', 175],
       [102, 'Bob', 21, 'M', 'IT', 78, 85, 'No', 163],
       [103, 'Charlie', 19, 'M', 'CS', 92, 95, 'Yes', 187],
       [104, 'David', 22, 'M', 'ECE', 88, 88, 'Yes', 176],
       [105, 'Eva', 20, 'F', 'IT', 90, 92, 'No', 182]], dtype=object)

In [ ]:
students.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student_ID  5 non-null      int64
 1   Name        5 non-null      object
 2   Age         5 non-null      int64
 3   Gender      5 non-null      object
 4   Department  5 non-null      object
 5   Marks       5 non-null      int64
 6   Attendance  5 non-null      int64
 7   Internship  5 non-null      object
dtypes: int64(4), object(4)
memory usage: 452.0+ bytes

In [ ]:
students['Department'].unique()

array(['CS', 'IT', 'ECE'], dtype=object)

# [3] Selection

---

In [ ]:

students['Marks']

0    85
1    78
2    92
3    88
4    90
Name: Marks, dtype: int64

In [ ]:
students[['Name', 'Department', 'Marks']]

      Name Department  Marks
0    Alice         CS     85
1      Bob         IT     78
2  Charlie         CS     92
3    David        ECE     88
4      Eva         IT     90

In [ ]:
students.iloc[0:3]

   Student_ID     Name  Age Gender Department  Marks  Attendance Internship
0         101    Alice   20      F         CS     85          90        Yes
1         102      Bob   21      M         IT     78          85         No
2         103  Charlie   19      M         CS     92          95        Yes

In [ ]:
students[students['Attendance'] > 90]

   Student_ID     Name  Age Gender Department  Marks  Attendance Internship
2         103  Charlie   19      M         CS     92          95        Yes
4         105      Eva   20      F         IT     90          92         No

In [ ]:
students.sort_values(by='Marks')

   Student_ID     Name  Age Gender Department  Marks  Attendance Internship
1         102      Bob   21      M         IT     78          85         No
0         101    Alice   20      F         CS     85          90        Yes
3         104    David   22      M        ECE     88          88        Yes
4         105      Eva   20      F         IT     90          92         No
2         103  Charlie   19      M         CS     92          95        Yes

#[4] Missing Data

---

In [ ]:
students.isnull().sum()

Student_ID    0
Name          0
Age           0
Gender        0
Department    0
Marks         0
Attendance    0
Internship    0
dtype: int64

In [ ]:
students['Marks'].fillna(students['Marks'].mean(), inplace=True)

/tmp/ipython-input-4257595247.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  students['Marks'].fillna(students['Marks'].mean(), inplace=True)

In [ ]:
students.dropna()

   Student_ID     Name  Age Gender Department  Marks  Attendance Internship
0         101    Alice   20      F         CS     85          90        Yes
1         102      Bob   21      M         IT     78          85         No
2         103  Charlie   19      M         CS     92          95        Yes
3         104    David   22      M        ECE     88          88        Yes
4         105      Eva   20      F         IT     90          92         No

In [ ]:
students.notna()

   Student_ID  Name   Age  Gender  Department  Marks  Attendance  Internship
0        True  True  True    True        True   True        True        True
1        True  True  True    True        True   True        True        True
2        True  True  True    True        True   True        True        True
3        True  True  True    True        True   True        True        True
4        True  True  True    True        True   True        True        True

In [ ]:
students.interpolate()

/tmp/ipython-input-1077483655.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  students.interpolate()

   Student_ID     Name  Age Gender Department  Marks  Attendance Internship
0         101    Alice   20      F         CS     85          90        Yes
1         102      Bob   21      M         IT     78          85         No
2         103  Charlie   19      M         CS     92          95        Yes
3         104    David   22      M        ECE     88          88        Yes
4         105      Eva   20      F         IT     90          92         No

In [ ]:
students.replace(20, 21)

   Student_ID     Name  Age Gender Department  Marks  Attendance Internship
0         101    Alice   21      F         CS     85          90        Yes
1         102      Bob   21      M         IT     78          85         No
2         103  Charlie   19      M         CS     92          95        Yes
3         104    David   22      M        ECE     88          88        Yes
4         105      Eva   21      F         IT     90          92         No

#[5] Removing Duplicates

---

In [ ]:
students.duplicated()

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [ ]:
students.drop_duplicates()

   Student_ID     Name  Age Gender Department  Marks  Attendance Internship
0         101    Alice   20      F         CS     85          90        Yes
1         102      Bob   21      M         IT     78          85         No
2         103  Charlie   19      M         CS     92          95        Yes
3         104    David   22      M        ECE     88          88        Yes
4         105      Eva   20      F         IT     90          92         No

#[6] Data Type Conversion


---

In [ ]:
students.astype({'Age': 'float'})

   Student_ID     Name   Age Gender Department  Marks  Attendance Internship
0         101    Alice  20.0      F         CS     85          90        Yes
1         102      Bob  21.0      M         IT     78          85         No
2         103  Charlie  19.0      M         CS     92          95        Yes
3         104    David  22.0      M        ECE     88          88        Yes
4         105      Eva  20.0      F         IT     90          92         No

In [ ]:

students['Name_numeric'] = pd.to_numeric(students['Name'], errors='coerce')

display(students[['Name', 'Name_numeric']].head())

      Name  Name_numeric
0    Alice           NaN
1      Bob           NaN
2  Charlie           NaN
3    David           NaN
4      Eva           NaN

In [ ]:

print(students.dtypes)

Student_ID        int64
Name             object
Age               int64
Gender           object
Department       object
Marks             int64
Attendance        int64
Internship       object
Name_numeric    float64
dtype: object

In [ ]:
students_converted = students.convert_dtypes()

print('\nafter convert_dtypes():')
print(students_converted.dtypes)

display(students_converted.head())

after convert_dtypes():
Student_ID               Int64
Name            string[python]
Age                      Int64
Gender          string[python]
Department      string[python]
Marks                    Int64
Attendance               Int64
Internship      string[python]
Name_numeric             Int64
dtype: object

,Student_ID,Name,Age,Gender,Department,Marks,Attendance,Internship,Name_numeric
0,101,Alice,20,F,CS,85,90,Yes,<NA>
1,102,Bob,21,M,IT,78,85,No,<NA>
2,103,Charlie,19,M,CS,92,95,Yes,<NA>
3,104,David,22,M,ECE,88,88,Yes,<NA>
4,105,Eva,20,F,IT,90,92,No,<NA>

# [7]Operations

---

In [ ]:
students['Total_Score'] = students['Marks'] + students['Attendance']

In [ ]:
students['Marks'].mean()

np.float64(86.6)

In [ ]:
students[students['Internship'] == 'Yes']

,Student_ID,Name,Age,Gender,Department,Marks,Attendance,Internship,Total_Score
0,101,Alice,20,F,CS,85,90,Yes,175
2,103,Charlie,19,M,CS,92,95,Yes,187
3,104,David,22,M,ECE,88,88,Yes,176

#[8] Merge

---

In [ ]:
fees = pd.DataFrame({
    'Student_ID': [101, 102, 103, 104, 105],
    'Fees_Paid': ['Yes', 'No', 'Yes', 'Yes', 'No']
})

In [ ]:
merged_df = pd.merge(students, fees, on='Student_ID')

#[9] Grouping

---

In [ ]:
students.groupby('Department')['Marks'].mean()

Department
CS     88.5
ECE    88.0
IT     84.0
Name: Marks, dtype: float64

In [ ]:
students.groupby('Department').size()

Department
CS     2
ECE    1
IT     2
dtype: int64